Island:
  Admin:
    Structure:
      # Item Material used to select the SpawnZone that can't be edited by any player
      SpawnZoneSelector: "GOLDEN_AXE"
Raid:
  RaidFinder:
    Menu:
      Exit:
        Item: 'RED_BED'
        ItemSlot: 0
      Raid:
        Item: 'RED_CONCRETE'
        ItemSlot: 4
      Next:
        Item: 'LIME_CONCRETE'
        ItemSlot: 8
    ScoutTime: 30
    BossBar:
      Color: "RED"
  Raid:
    RaidTime: 300
    BossBar:
      Color: "RED"